"""
Gradient-boosting health model with SHAP explanations (M8 Stage C).

FRAMING (repeated from ``sensor_sim.py``; read that module's docstring
first): the channels this model is trained on are self-generated by this
project, with a documented rule wiring exactly two channels to a degradation
ramp. Nothing here demonstrates predictive maintenance (PdM) on a real fab.
Every metric in this module is a DETECTION-QUALITY score against the KNOWN
synthetic ground truth attached at generation time - ROC AUC against the
``degraded`` label we ourselves assigned, SHAP importance against the two
channels we ourselves wired, detection delay/false-alarm rate against the
onset day we ourselves drew. Read every AUC, delay, and ranking in this
module as "did the model recover the rule we wrote", never as "how well
would this work on a real tool".

Why episode-level train/test split, not day-level
------------------------------------------------------
Rolling-window features (see ``build_features``) make consecutive days of
the SAME tool-episode highly correlated: day t's rolling mean/std/slope
shares most of its input window with day t+1's. A day-level random split
would put near-duplicate rows (overlapping windows of the same ramp) on both
sides of the train/test boundary, so the model could "test well" simply by
memorizing the shape of a ramp it partially saw in training - leakage, not
generalization, and it would inflate AUC in a way that has nothing to do
with detection quality. Splitting whole EPISODES (independent seeds, onset
days, and severities - see ``sensor_sim.make_episodes``) into train vs test
means the test episodes' onset day, severity, and noise realization are
never seen in any form during training, so held-out AUC reflects whether the
model recovered the GENERAL rule (two wired channels rising with a ramp)
rather than one episode's particular draw.

Causality of features (documented, checked in GATE 2 of pdm_check.py)
--------------------------------------------------------------------------
``build_features`` computes, for day t, a trailing window over
``[t - window + 1, t]`` ONLY - it never reads day t+1 or later. This is
checked structurally (GATE 2): recomputing features after overwriting every
row's channel values on days AFTER that row's own day with garbage produces
BYTE-IDENTICAL feature rows, proving no future day's value can leak into
day t's features no matter how it is corrupted.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import roc_auc_score

HERE = Path(__file__).resolve()
SRC = HERE.parents[1]
for sub in ("monitoring",):
    p = str(SRC / sub)
    if p not in sys.path:
        sys.path.insert(0, p)

from detectors import fit_baseline, ewma_chart, alarm_days  # noqa: E402
from evaluation import evaluate_single, aggregate  # noqa: E402

from sensor_sim import CHANNELS, DEGRADATION_WIRING  # noqa: E402

#: Trailing window (days) for rolling feature summaries. 7 days: long enough
#: to average out one day of AR(1) noise, short enough to still be a LOCAL
#: read near the onset rather than smearing the whole episode together.
ROLLING_WINDOW_DAYS = 7

#: Fixed random_state for GradientBoostingClassifier (reproducibility gate).
GB_RANDOM_STATE = 42

#: Health-score threshold used to turn a per-day probability into an alert
#: day for the detection-delay / false-alarm comparison (see
#: ``alert_days_from_scores``). 0.5 is the plain probability midpoint, not
#: tuned to this data - a fixed, explainable choice.
DEFAULT_ALERT_THRESHOLD = 0.5


def build_features(frame: pd.DataFrame, channels: tuple = CHANNELS,
                   window: int = ROLLING_WINDOW_DAYS) -> pd.DataFrame:
    """Per (tool, day) trailing rolling-window features: mean, std, slope.

    Strictly causal: day t's features summarize ONLY
    ``frame`` rows for that tool with day in ``[t - window + 1, t]``
    (``pandas.Series.rolling`` with default ``closed="right"``, i.e. no
    future days). Slope is the OLS slope of channel value against day index
    within the trailing window (rate of change, not just level). The first
    ``window - 1`` days of an episode have a shorter (but still trailing-only)
    window, per pandas rolling's ``min_periods=1`` default here - never a
    forward-looking one.

    Returns a frame indexed like the input's (episode_id, tool_id, day) plus
    one ``{channel}_mean``, ``{channel}_std``, ``{channel}_slope`` column per
    channel, sorted by (episode_id, tool_id, day) so grouping/merging is safe.
    """
    frame = frame.sort_values(["episode_id", "tool_id", "day"]).reset_index(drop=True)
    feats = {"episode_id": frame["episode_id"], "tool_id": frame["tool_id"],
             "day": frame["day"]}

    def _slope(x: np.ndarray) -> float:
        n = len(x)
        if n < 2:
            return 0.0
        idx = np.arange(n, dtype=float)
        idx_c = idx - idx.mean()
        denom = (idx_c ** 2).sum()
        if denom == 0.0:
            return 0.0
        return float((idx_c * (x - x.mean())).sum() / denom)

    grouped = frame.groupby(["episode_id", "tool_id"], sort=False)
    for ch in channels:
        roll = grouped[ch].rolling(window=window, min_periods=1)
        feats[f"{ch}_mean"] = roll.mean().reset_index(drop=True)
        feats[f"{ch}_std"] = roll.std(ddof=0).fillna(0.0).reset_index(drop=True)
        feats[f"{ch}_slope"] = grouped[ch].transform(
            lambda s: s.rolling(window=window, min_periods=1).apply(_slope, raw=True)
        ).reset_index(drop=True)

    out = pd.DataFrame(feats)
    out["degraded"] = frame["degraded"].to_numpy()
    return out


def feature_columns(channels: tuple = CHANNELS) -> list:
    """The model's input column names, in a fixed order (for SHAP alignment)."""
    cols = []
    for ch in channels:
        cols += [f"{ch}_mean", f"{ch}_std", f"{ch}_slope"]
    return cols


def episodes_to_feature_table(episodes: list, channels: tuple = CHANNELS,
                              window: int = ROLLING_WINDOW_DAYS) -> pd.DataFrame:
    """Build one concatenated feature table across a list of episodes.

    ``episodes`` is the list returned by ``sensor_sim.make_episodes``
    (``[{"config": EpisodeConfig, "frame": ...}, ...]``). Features are built
    PER EPISODE (each episode's rolling windows never cross into another
    episode's frame) then concatenated, preserving ``episode_id``.
    """
    parts = [build_features(ep["frame"], channels=channels, window=window)
             for ep in episodes]
    return pd.concat(parts, ignore_index=True)


def split_episodes(episodes: list, n_train: int) -> tuple:
    """Split a list of episodes into train (first ``n_train``) and test (rest).

    Episode order is the order ``sensor_sim.make_episodes`` generated them in
    (``episode_id`` 0..N-1, each with its own independent seed/onset/alpha),
    so this is equivalent to "train on episodes 1..k, test on the rest" with
    no shuffling - keeps the split trivially reproducible and auditable.
    """
    if n_train >= len(episodes):
        raise ValueError(f"n_train ({n_train}) must be < number of episodes ({len(episodes)})")
    return episodes[:n_train], episodes[n_train:]


def train_health_model(train_episodes: list, channels: tuple = CHANNELS,
                       window: int = ROLLING_WINDOW_DAYS,
                       random_state: int = GB_RANDOM_STATE
                       ) -> tuple:
    """Fit a GradientBoostingClassifier on the training episodes' features.

    Predicts the "degradation active" label (``degraded``, ground truth from
    ``sensor_sim``) per tool-day from the causal rolling features. Fixed
    ``random_state`` for reproducibility (GATE 1). Returns
    ``(model, feature_table)`` where ``feature_table`` is the exact frame the
    model was fit on (for SHAP, see ``shap_importance``).
    """
    table = episodes_to_feature_table(train_episodes, channels=channels, window=window)
    cols = feature_columns(channels)
    model = GradientBoostingClassifier(random_state=random_state)
    model.fit(table[cols], table["degraded"].astype(int))
    return model, table


def score_test_episodes(model, test_episodes: list, channels: tuple = CHANNELS,
                        window: int = ROLLING_WINDOW_DAYS) -> pd.DataFrame:
    """Health score (predicted probability of "degradation active") per tool-day.

    Returns the held-out feature table with an added ``health_score`` column
    (``model.predict_proba(...)[:, 1]``) and the ``degraded`` ground-truth
    label carried through for scoring.
    """
    table = episodes_to_feature_table(test_episodes, channels=channels, window=window)
    cols = feature_columns(channels)
    table = table.copy()
    table["health_score"] = model.predict_proba(table[cols])[:, 1]
    return table


def held_out_auc(scored: pd.DataFrame) -> float:
    """ROC AUC of ``health_score`` against the ``degraded`` ground truth.

    Measures detection quality against the KNOWN synthetic label, not
    predictive power (see module docstring): this is "did the model separate
    the tool-days we ourselves marked degraded from the ones we marked
    clean", on episodes never used to fit the model.
    """
    return float(roc_auc_score(scored["degraded"].astype(int), scored["health_score"]))


def shap_importance(model, train_table: pd.DataFrame,
                    channels: tuple = CHANNELS) -> pd.DataFrame:
    """Global SHAP importance per channel (TreeExplainer, mean |SHAP value|).

    Ranks CHANNELS (not individual mean/std/slope features) by summing the
    mean absolute SHAP value of their three engineered features, so the
    ranking answers "which raw sensor channel mattered", directly comparable
    to ``sensor_sim.DEGRADATION_WIRING`` for GATE 4 (the two wired channels
    should rank top-2).
    """
    import shap
    cols = feature_columns(channels)
    explainer = shap.TreeExplainer(model)
    sv = explainer.shap_values(train_table[cols])
    mean_abs = np.abs(sv).mean(axis=0)
    per_feature = pd.Series(mean_abs, index=cols)

    rows = []
    for ch in channels:
        ch_cols = [f"{ch}_mean", f"{ch}_std", f"{ch}_slope"]
        rows.append({"channel": ch, "mean_abs_shap": float(per_feature[ch_cols].sum())})
    out = pd.DataFrame(rows).sort_values("mean_abs_shap", ascending=False).reset_index(drop=True)
    out["rank"] = np.arange(1, len(out) + 1)
    return out


def alert_days_from_scores(scored: pd.DataFrame, episode_id: int, tool_id: str,
                           threshold: float = DEFAULT_ALERT_THRESHOLD) -> pd.DataFrame:
    """Turn one (episode, tool)'s per-day ``health_score`` into an ``alarm`` frame.

    ``episode_id`` AND ``tool_id`` both select the rows: tool_id labels
    (e.g. "LITHO-1") repeat across test episodes, so filtering by tool_id
    alone would mix days from different episodes onto the same day index
    (duplicate labels, which breaks ``evaluation.evaluate_single``'s
    ``reindex``). Same shape/vocabulary as ``monitoring.detectors`` output
    (indexed by day, boolean ``alarm`` column) so
    ``monitoring.evaluation.evaluate_single`` can score it identically to an
    EWMA/control-chart detector.
    """
    tdf = scored.loc[(scored["episode_id"] == episode_id)
                      & (scored["tool_id"] == tool_id)].sort_values("day")
    alarm = (tdf["health_score"].to_numpy() >= threshold)
    return pd.DataFrame({"value": tdf["health_score"].to_numpy(), "alarm": alarm},
                        index=tdf["day"].to_numpy())


def _episode_window_and_baseline(config) -> tuple:
    """One [{t_start,t_end,type}] window (days, DAY=1) and clean baseline days.

    Reuses ``monitoring.evaluation``'s day-indexed vocabulary (``DAY=24.0`` in
    that module is an hours-per-day conversion; here the sensor sim is
    already in day units, so windows are passed with ``t_start``/``t_end`` in
    RAW DAY NUMBERS and ``evaluate_single``'s ``_day_windows`` divides by its
    own ``DAY`` constant - to keep the two modules' day units consistent, the
    window bounds are pre-scaled by ``evaluation.DAY`` here, undoing that
    division exactly. Baseline days are every day strictly before onset.
    """
    from evaluation import DAY as EVAL_DAY
    window = {
        "type": "degradation",
        "t_start": config.onset_day * EVAL_DAY,
        "t_end": (config.onset_day + config.duration_days) * EVAL_DAY,
    }
    baseline_days = list(range(0, config.onset_day))
    return [window], baseline_days


def evaluate_health_scores(scored: pd.DataFrame, test_episodes: list,
                          threshold: float = DEFAULT_ALERT_THRESHOLD) -> dict:
    """Detection-delay / false-alarm evaluation of the health score, per episode.

    For each test episode's DEGRADING tool only (the one carrying the
    ``degraded`` ground truth), thresholds ``health_score`` into alarms
    (``alert_days_from_scores``) and scores them with
    ``monitoring.evaluation.evaluate_single`` / ``aggregate`` - the SAME
    functions and vocabulary (detection delay, false-alarm rate, precision,
    recall) used to score the M5 EWMA/control-chart detectors, so the two
    methods are compared on identical ground. Returns the ``aggregate(...)``
    dict (see ``evaluation.py``).
    """
    singles = []
    for ep in test_episodes:
        config = ep["config"]
        degrading_tool = f"{config.station}-{config.degrading_tool_index + 1}"
        det = alert_days_from_scores(scored, config.episode_id, degrading_tool,
                                     threshold=threshold)
        series = det["value"]
        windows, baseline_days = _episode_window_and_baseline(config)
        singles.append(evaluate_single(det, windows, series, baseline_days))
    return aggregate(singles)


def evaluate_ewma_baseline(test_episodes: list, channel: str,
                          lam: float = 0.2, L: float = 3.0) -> dict:
    """EWMA-on-one-channel baseline, scored with the same evaluation vocabulary.

    Applies ``monitoring.detectors.ewma_chart`` to the single strongest wired
    channel (chosen by the caller - see ``pdm_check.py``) of each test
    episode's degrading tool, fitting ``(center, sigma)`` on that episode's
    own pre-onset clean days (leakage-free, same discipline as M5). Returns
    the same ``aggregate(...)`` shape as ``evaluate_health_scores`` so the two
    can sit side by side in one comparison table.
    """
    singles = []
    for ep in test_episodes:
        config = ep["config"]
        frame = ep["frame"]
        degrading_tool = f"{config.station}-{config.degrading_tool_index + 1}"
        tdf = frame.loc[frame["tool_id"] == degrading_tool].sort_values("day")
        series = pd.Series(tdf[channel].to_numpy(), index=tdf["day"].to_numpy())
        windows, baseline_days = _episode_window_and_baseline(config)
        center, sigma = fit_baseline(series, baseline_days)
        det = ewma_chart(series, center, sigma, lam=lam, L=L)
        singles.append(evaluate_single(det, windows, series, baseline_days))
    return aggregate(singles)


def comparison_table(gb_agg: dict, ewma_agg: dict, ewma_channel: str) -> pd.DataFrame:
    """Side-by-side GB-health-score vs EWMA(single channel) detection-quality table.

    Both rows come from ``monitoring.evaluation.aggregate`` on the SAME
    held-out episodes, so the columns are directly comparable. EWMA being
    competitive with (or better than) the gradient-boosting score is an
    accepted, interesting outcome here, not a failure of either method (see
    module docstring: this measures detection quality, not model superiority).
    """
    rows = [
        {"method": "gradient_boosting (all channels)",
         "mean_detection_delay_days": gb_agg["mean_detection_delay_days"],
         "false_alarm_rate": gb_agg["false_alarm_rate"],
         "precision": gb_agg["precision"], "recall": gb_agg["recall"]},
        {"method": f"ewma ({ewma_channel} only)",
         "mean_detection_delay_days": ewma_agg["mean_detection_delay_days"],
         "false_alarm_rate": ewma_agg["false_alarm_rate"],
         "precision": ewma_agg["precision"], "recall": ewma_agg["recall"]},
    ]
    return pd.DataFrame(rows)


def health_score_to_severity(health_score: float, horizon_hours: float = 24.0) -> float:
    """Map a health score in [0, 1] to ``alert_priority.PriorityInputs.severity``.

    Minimal, documented hook: ``alert_priority.severity_from_alpha`` reads
    severity as "fractional process-time inflation after ``horizon_hours`` of
    degradation" (``alpha * horizon_hours``). This function repurposes the
    same [0, 1]-ish scale directly: ``severity = health_score`` (health_score
    is already a probability in [0, 1], the same range ``alpha * horizon_hours``
    occupies for the small alphas used in this project's demonstrations - see
    ``ALPHA_RANGE`` in ``sensor_sim.py``, whose upper bound times a 24h horizon
    is 0.06 * 24 = 1.44). No rescaling or tuning: this is a plumbing hook, not
    a second model. Callers build a full ``PriorityInputs`` by supplying this
    value as ``severity`` alongside the station's own
    ``bottleneck_criticality`` and ``cost_exposure_per_hour``
    (``alert_priority.compute_priority`` computes those two from the
    station/cfg; this function only replaces the ``severity`` term with a
    measured health score instead of a known ``alpha``).
    """
    return float(np.clip(health_score, 0.0, 1.0))
